### ISSUE TITLE
Rename `ByteString`

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell-streaming/streaming-bytestring#6]
Would it be too radical a change to rename `ByteString`? I (for one) think a streaming bytestring is a sufficiently different type to warrant its own name (`ByteStream`?)

This would also make the haddocks much clearer - no need to hover over a `ByteString` hyperlink to ascertain which it is.

Thanks :)

**Comment by andrewthad** [comment]
I'm in favor of this, and I think the name `ByteStream` is very apt. In fact, it's the name I use for [streams of bytes](https://github.com/andrewthad/packed/blob/7ce634e68be50eb93ca91b2ac3ef9cf4c1db2a46/src/Packed/Bytes/Stream.hs) in another library I'm currently working on.

@ivan-m @treeowl Do either of you have an opinion on this?

**Comment by ivan-m** [comment]
If it was new, maybe. At this point in time, enough people have started using it that I think it would cause confusion.

**Comment by mitchellwrosen** [comment]
A couple thoughts about that @ivan-m:

- This repo only has 5 GitHub stars (heh, sorry, it felt like this fact was relevant. The library's awesome)
- A type alias could be introduced, with a deprecation warning on `ByteString` to be removed eventually)

This is assuming renaming the type is a good idea and should be done in whatever way possible. If it's not worth the trouble, that's fine too :)

**Comment by seagreen** [comment]
As someone new to the library, `ByteStream` is a lot easier to understand than `ByteString`. I'm used to the same name being reused by different modules, but it's strange to have such a common name reused with a different kind.

Of course, even if you agree that `ByteStream` is better for people new to the library, whether it's worth the switch depends on how many people you expect to use it in the future compared to how many are using it now:)

**Comment by ivan-m** [comment]
I never star github repos, so I don't think that's good metric :)  A better indicator would be the number of reverse dependencies (a type alias doesn't help with the package name and import statement). 

Also, I kind of like the justification that it's lazy bytestrings done right.

**Comment by seagreen** [comment]
It's at 13, which is very respectable!

However, `bytestring` is at 4638, so if that's the library you're hunting most of your users are in the future=)

**Comment by ivan-m** [comment]
I'm using it as a metric of "this will break existing code".

However, there are some odd spots in this library; I would support a re-implementation with a new name (i.e. sufficiently different API that people would have to update how they use this library anyway).

**Comment by mitchellwrosen** [comment]
That makes sense. If making a major version bump, it's always better to get in as many breaking changes as possible.

**Comment by mitchellwrosen** [comment]
Re this comment above:

> Also, I kind of like the justification that it's lazy bytestrings done right.

I don't think this streaming bytestring type totally replaces all uses of lazy bytestrings, only those that use `unsafePerformIO` to get a similar "streaming" effect. For example, [`httpLbs`](https://hackage.haskell.org/package/http-client-0.5.12/docs/Network-HTTP-Client.html#v:httpLbs) returns a fully-evaluated lazy bytestring. I assume it's not strict to avoid excessive copying as a response is read incrementally.

**Comment by chessai** [comment]
I am in favour of this. The `bytestring` library will outweigh any other library which might dare to name a type `ByteString`. The breakage it will cause seems justified and explainable. I suggest the following update plan:

1. Introduce `Streaming.ByteString`, `Streaming.ByteString.Char8`, and `Streaming.ByteString.Internal`, with a new data type, equivalent to `Data.ByteString.Streaming.Internal.ByteString`, but named `ByteStream`.
2. Deprecate `Data.ByteString.Streaming`, `Data.ByteString.Streaming.Char8`, `Data.ByteString.Streaming.Internal`. Make uses of all functions in Data.ByteString.Streaming* uncompilable using `TypeError` (similar to the use of `Whoops` in Data.Map). The custom type error can just point them to the relevant function/replacement module. (I don't expect this to be very inconvenient; lots of uses of `streaming` libraries import relevant `streaming` modules qualified due to name clashes anyway).
3. Make a majour release. On the subsequent majour release, just remove `Data.ByteString.Streaming*`.

**Comment by fosskers** [comment]
Shall we go ahead with this? I was going to make a release today to include the recent perf improvements, but could hold off it we want to move forward with this change too.

**Comment by chessai** [comment]
Yes, I think so. The name clashing has been really annoying in the past (I
prefer unqualified type imports, since I spend most of my time reading type
signatures).

Additionally,

Preferably we would have

Streaming.ByteString

or something like that. The module naming here is silly. We got it right in
the original streaming package.

**Comment by fosskers** [comment]
I'll put a PR together with renames + deprecations. `streaming-attoparsec` will also need to be updated.

**Comment by fosskers** [comment]
Once my other PRs get through I'm going to work on this. Should be done in a few days.

**Comment by fosskers** [comment]
Now that the documentation overhaul is complete, we can begin the renaming.

**Comment by fosskers** [comment]
Starting this now.

**Comment by fosskers** [comment]
The PR is ready, go nuts.

**Comment by chessai** [comment]
awesome, thanks!

**Comment by fosskers** [comment]
Just dealing with some Hackage credential issues, but otherwise a release is ready to go.
